### ISSUE TITLE
Create a wheel of emotions

### ISSUE THREAD

**Issue by hamadhassan** [Saqi-CS/OG-Spinner-Wheel#2]
Add the following wheel emotions
1. Model
2. K-Pop
3. Dare
4. Crush 
5. Animal
6. Thunder Cat
7. Model

**Comment by Syed-Zulqarnain-Haider** [comment]
I am interested in making an emotion wheel.

**Comment by hamadhassan** [comment]
Task Assigned

**Comment by hamadhassan** [comment]
Task completed
